CREATE TABLE IF NOT EXISTS `_DB_PREFIX_omniva_product` (
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `id_product` INT(10) NOT NULL,
    `is_18_plus` TINYINT(1) NOT NULL,
    `is_fragile` TINYINT(1) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=_MYSQL_ENGINE_ DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
89485368X846aModer416xa1656ax1